{{- if and (not .Values.bridges.rss.existingSecret.registration) .Values.bridges.rss.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.rss.registrationSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  registration.yaml: |
    id: {{ .Values.bridges.rss.registration.id }}
    {{ if .Values.bridges.rss.registration.url }}
    url: {{ .Values.bridges.rss.registration.url }}
    {{- else -}}
    url: http://{{ include "matrix.fullname" .}}-bridge-rss:{{ .Values.bridges.rss.config.app_port }}
    {{- end }}
    rate_limited: false
    sender_localpart: {{ .Values.bridges.rss.registration.sender_localpart }}
    as_token: "{{ include "matrix.rss.as_token" . }}"
    hs_token: "{{ include "matrix.rss.hs_token" . }}"
    namespaces:
      users:
        - exclusive: true
          regex: "^@rss.*:{{ .Values.matrix.serverName }}$"
        - exclusive: true
          regex: "^@{{ .Values.bridges.rss.config.matrix_user }}:{{ .Values.matrix.serverName }}$"
    {{- if .Values.bridges.rss.encryption }}
    de.sorunome.msc2409.push_ephemeral: true
    push_ephemeral: true
    {{- end }}
{{- end }}
